// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqzndeckclooyrsaauxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indxem5kZWNrY2xvb3lyc2FhdXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzU5ODksImV4cCI6MjA2NDAxMTk4OX0.rI8aHMIFBGqWykodMnyfqk7xuKUJPmaTpH0G9chBMrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);